using Curfew.Core;

namespace Curfew.Service;

/// <summary>
/// Applies the configured Cloudflare content filter (and, optionally, the
/// firewall block on third-party DNS-over-HTTPS resolvers) to the machine.
/// </summary>
/// <remarks>
/// <para>
/// Two independent PowerShell scripts are run as SYSTEM: one pins (or clears)
/// the Cloudflare DNS servers on every active adapter, and one adds (or removes)
/// the DoH bypass firewall rules. Both scripts are generated by the pure helpers
/// in <see cref="Curfew.Core"/> and are themselves idempotent, so this applier is
/// safe to call repeatedly — in particular it is re-run on every network change
/// so the filter stays pinned as adapters come and go.
/// </para>
/// <para>
/// The two steps are deliberately decoupled: a failure applying the DNS filter
/// must not prevent the DoH guard from being reconciled, and vice versa. Each
/// step records its outcome to <see cref="ServiceLog"/> for on-device
/// diagnostics; the caller still wraps the whole operation in its own
/// try/catch and structured logging.
/// </para>
/// </remarks>
internal static class ContentFilterApplier
{
    // Persisted settings keys. These string literals are a cross-component
    // contract shared with the WinUI app and must not change.
    private const string FilterModeKey = "dns_filter_mode";
    private const string BlockDohKey = "block_doh_bypass";

    /// <summary>
    /// Reconciles the machine's DNS content filter and DoH bypass block with the
    /// supplied settings. Never throws for an individual step's PowerShell
    /// failure — those are logged and the next step still runs.
    /// </summary>
    /// <param name="settings">The open settings store to read configuration from.</param>
    public static void Apply(SettingsStore settings)
    {
        ArgumentNullException.ThrowIfNull(settings);

        var mode = ContentFilter.Parse(settings.Get(FilterModeKey));

        // Step 1: pin the chosen Cloudflare resolvers (or reset adapters to DHCP
        // when filtering is Off).
        RunStep(
            $"DNS filter ({ContentFilter.ToSetting(mode)})",
            ContentFilter.BuildApplyScript(mode));

        // Step 2: reconcile the DoH bypass firewall block. The block is only
        // meaningful while a filter is active — with no filter there is nothing
        // to bypass — so it is always cleared when the filter is Off, regardless
        // of the persisted preference.
        var blockDoh = mode != FilterMode.Off && settings.GetBool(BlockDohKey, true);
        RunStep(
            blockDoh ? "DoH bypass block" : "DoH bypass clear",
            blockDoh ? DohGuard.BuildBlockScript() : DohGuard.BuildClearScript());
    }

    /// <summary>
    /// Runs one PowerShell reconciliation step, recording a non-zero or failed
    /// exit code without letting it abort the remaining steps.
    /// </summary>
    private static void RunStep(string description, string script)
    {
        int exitCode = PowerShellRunner.Run(script);
        if (exitCode != 0)
        {
            EventLog.Append(CurfewPaths.EventLogFile, CurfewEventKind.FilterFailure, $"{description} ({exitCode})");
            // PowerShellRunner returns -1 when the process could not be launched
            // or had to be killed after timing out; any other non-zero value is
            // the script's own exit code. The generated scripts use
            // SilentlyContinue, so a non-zero result is unexpected and worth a log.
            ServiceLog.Write($"content filter step '{description}' returned exit code {exitCode}");
        }
    }
}
